name: Auto Push to GitHub

on:
  push:
    branches:
      - main  # یا هر branch دیگه‌ای که می‌خواید

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Commit & Push changes
        run: |
          git config --global user.name "your-github-username"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Auto commit changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
